package com.vedbiz.websocketclient;

/**
 * Created by User on 30-01-2018.
 */

public class CMSRequestStrings {

   final public static String cancelReservation = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"CancelReservationRequest\",\"type\":\"object\",\"properties\":{\"reservationId\":{\"type\":\"integer\"}},\"additionalProperties\":false,\"required\":[\"reservationId\"]}";
    final public static String changeAvailability ="{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ChangeAvailabilityRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"type\":{\"type\":\"string\",\"enum\":[\"Inoperative\",\"Operative\"]}},\"additionalProperties\":false,\"required\":[\"connectorId\",\"type\"]}";
    final public static String changeConfiguration = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ChangeConfigurationRequest\",\"type\":\"object\",\"properties\":{\"key\":{\"type\":\"string\",\"maxLength\":50},\"value\":{\"type\":\"string\",\"maxLength\":500}},\"additionalProperties\":false,\"required\":[\"key\",\"value\"]}";
    final public static  String clearCache = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ClearCacheRequest\",\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}";
    final public static  String clearChargingProfile = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ClearChargingProfileRequest\",\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"integer\"},\"connectorId\":{\"type\":\"integer\"},\"chargingProfilePurpose\":{\"type\":\"string\",\"enum\":[\"ChargePointMaxProfile\",\"TxDefaultProfile\",\"TxProfile\"]},\"stackLevel\":{\"type\":\"integer\"}},\"additionalProperties\":false}";
    final public static String dataTransfer = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"DataTransferRequest\",\"type\":\"object\",\"properties\":{\"vendorId\":{\"type\":\"string\",\"maxLength\":255},\"messageId\":{\"type\":\"string\",\"maxLength\":50},\"data\":{\"type\":\"string\"}},\"additionalProperties\":false,\"required\":[\"vendorId\"]}";
    final public static String getCompositeSchedule = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetCompositeScheduleRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"duration\":{\"type\":\"integer\"},\"chargingRateUnit\":{\"type\":\"string\",\"enum\":[\"A\",\"W\"]}},\"additionalProperties\":false,\"required\":[\"connectorId\",\"duration\"]}";
    final public static  String getConfiguration = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetConfigurationRequest\",\"type\":\"object\",\"properties\":{\"key\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"maxLength\":50}}},\"additionalProperties\":false}";
    final public static String getDiagnostics = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetDiagnosticsRequest\",\"type\":\"object\",\"properties\":{\"location\":{\"type\":\"string\",\"format\":\"uri\"},\"retries\":{\"type\":\"integer\"},\"retryInterval\":{\"type\":\"integer\"},\"startTime\":{\"type\":\"string\",\"format\":\"date-time\"},\"stopTime\":{\"type\":\"string\",\"format\":\"date-time\"}},\"additionalProperties\":false,\"required\":[\"location\"]}";
    final public static String getLocalListVersion = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"GetLocalListVersionRequest\",\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}";
    final public static String remoteStartTransaction = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"RemoteStartTransactionRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"idTag\":{\"type\":\"string\",\"maxLength\":20},\"chargingProfile\":{\"type\":\"object\",\"properties\":{\"chargingProfileId\":{\"type\":\"integer\"},\"transactionId\":{\"type\":\"integer\"},\"stackLevel\":{\"type\":\"integer\"},\"chargingProfilePurpose\":{\"type\":\"string\",\"enum\":[\"ChargePointMaxProfile\",\"TxDefaultProfile\",\"TxProfile\"]},\"chargingProfileKind\":{\"type\":\"string\",\"enum\":[\"Absolute\",\"Recurring\",\"Relative\"]},\"recurrencyKind\":{\"type\":\"string\",\"enum\":[\"Daily\",\"Weekly\"]},\"validFrom\":{\"type\":\"string\",\"format\":\"date-time\"},\"validTo\":{\"type\":\"string\",\"format\":\"date-time\"},\"chargingSchedule\":{\"type\":\"object\",\"properties\":{\"duration\":{\"type\":\"integer\"},\"startSchedule\":{\"type\":\"string\",\"format\":\"date-time\"},\"chargingRateUnit\":{\"type\":\"string\",\"enum\":[\"A\",\"W\"]},\"chargingSchedulePeriod\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"startPeriod\":{\"type\":\"integer\"},\"limit\":{\"type\":\"number\",\"multipleOf\":0.1},\"numberPhases\":{\"type\":\"integer\"}},\"required\":[\"startPeriod\",\"limit\"]}},\"minChargingRate\":{\"type\":\"number\",\"multipleOf\":0.1}},\"required\":[\"chargingRateUnit\",\"chargingSchedulePeriod\"]}},\"required\":[\"chargingProfileId\",\"stackLevel\",\"chargingProfilePurpose\",\"chargingProfileKind\",\"chargingSchedule\"]}},\"additionalProperties\":false,\"required\":[\"idTag\"]}";
    final public static String remoteStopTransaction = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"RemoteStopTransactionRequest\",\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"integer\"}},\"additionalProperties\":false,\"required\":[\"transactionId\"]}";
    final public static String reserveNowRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ReserveNowRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"expiryDate\":{\"type\":\"string\",\"format\":\"date-time\"},\"idTag\":{\"type\":\"string\",\"maxLength\":20},\"parentIdTag\":{\"type\":\"string\",\"maxLength\":20},\"reservationId\":{\"type\":\"integer\"}},\"additionalProperties\":false,\"required\":[\"connectorId\",\"expiryDate\",\"idTag\",\"reservationId\"]}";
    final public static String resetRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"ResetRequest\",\"type\":\"object\",\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"Hard\",\"Soft\"]}},\"additionalProperties\":false,\"required\":[\"type\"]}";
    final public static String sendLocalListRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"SendLocalListRequest\",\"type\":\"object\",\"properties\":{\"listVersion\":{\"type\":\"integer\"},\"localAuthorizationList\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"idTag\":{\"type\":\"string\",\"maxLength\":20},\"idTagInfo\":{\"type\":\"object\",\"expiryDate\":{\"type\":\"string\",\"format\":\"date-time\"},\"parentIdTag\":{\"type\":\"string\",\"maxLength\":20},\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"Accepted\",\"Blocked\",\"Expired\",\"Invalid\",\"ConcurrentTx\"]}},\"required\":[\"status\"]}},\"required\":[\"idTag\"]}},\"updateType\":{\"type\":\"string\",\"enum\":[\"Differential\",\"Full\"]}},\"additionalProperties\":false,\"required\":[\"listVersion\",\"updateType\"]}";
    final public static String setChargingProfileRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"SetChargingProfileRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"},\"csChargingProfiles\":{\"type\":\"object\",\"properties\":{\"chargingProfileId\":{\"type\":\"integer\"},\"transactionId\":{\"type\":\"integer\"},\"stackLevel\":{\"type\":\"integer\"},\"chargingProfilePurpose\":{\"type\":\"string\",\"enum\":[\"ChargePointMaxProfile\",\"TxDefaultProfile\",\"TxProfile\"]},\"chargingProfileKind\":{\"type\":\"string\",\"enum\":[\"Absolute\",\"Recurring\",\"Relative\"]},\"recurrencyKind\":{\"type\":\"string\",\"enum\":[\"Daily\",\"Weekly\"]},\"validFrom\":{\"type\":\"string\",\"format\":\"date-time\"},\"validTo\":{\"type\":\"string\",\"format\":\"date-time\"},\"chargingSchedule\":{\"type\":\"object\",\"properties\":{\"duration\":{\"type\":\"integer\"},\"startSchedule\":{\"type\":\"string\",\"format\":\"date-time\"},\"chargingRateUnit\":{\"type\":\"string\",\"enum\":[\"A\",\"W\"]},\"chargingSchedulePeriod\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"startPeriod\":{\"type\":\"integer\"},\"limit\":{\"type\":\"number\",\"multipleOf\":0.1},\"numberPhases\":{\"type\":\"integer\"}},\"required\":[\"startPeriod\",\"limit\"]}},\"minChargingRate\":{\"type\":\"number\",\"multipleOf\":0.1}},\"required\":[\"chargingRateUnit\",\"chargingSchedulePeriod\"]}},\"required\":[\"chargingProfileId\",\"stackLevel\",\"chargingProfilePurpose\",\"chargingProfileKind\",\"chargingSchedule\"]}},\"additionalProperties\":false,\"required\":[\"connectorId\",\"csChargingProfiles\"]}";
    final public static String triggerMessageRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"TriggerMessageRequest\",\"type\":\"object\",\"properties\":{\"requestedMessage\":{\"type\":\"string\",\"enum\":[\"BootNotification\",\"DiagnosticsStatusNotification\",\"FirmwareStatusNotification\",\"Heartbeat\",\"MeterValues\",\"StatusNotification\"]},\"connectorId\":{\"type\":\"integer\"}},\"additionalProperties\":false,\"required\":[\"requestedMessage\"]}";
    final public static String unlockConnectorRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"UnlockConnectorRequest\",\"type\":\"object\",\"properties\":{\"connectorId\":{\"type\":\"integer\"}},\"additionalProperties\":false,\"required\":[\"connectorId\"]}";
    final public static String updateFirmwareRequest = "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"title\":\"UpdateFirmwareRequest\",\"type\":\"object\",\"properties\":{\"location\":{\"type\":\"string\",\"format\":\"uri\"},\"retries\":{\"type\":\"number\"},\"retrieveDate\":{\"type\":\"string\",\"format\":\"date-time\"},\"retryInterval\":{\"type\":\"number\"}},\"additionalProperties\":false,\"required\":[\"location\",\"retrieveDate\"]}";

}
